### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by dan1wang** [google/gts#303]
When running the `gts clean` command, I was stumped by 'tsconfig.json Not Found' error. Turns out there is an error with my "tsconfig.json" file, so it's really a parson error

**Comment by JustinBeckwith** [comment]
I just verified with the latest version that you get a more reasonable error with an invalid `tsconfig.json`:

```
sloth (master) $ npm run lint

> @justinbeckwith/sloth@5.0.0 lint /Users/beckwith/Code/sloth
> gts check

FatalError: tsconfig.json(13,1): error TS1005: '}' expected.

    at new FatalError (/Users/beckwith/Code/sloth/node_modules/tslint/lib/error.js:27:28)
    at Function.Linter.createProgram (/Users/beckwith/Code/sloth/node_modules/tslint/lib/linter.js:56:19)
    at createProgram (/Users/beckwith/Code/sloth/node_modules/gts/build/src/lint.js:79:28)
    at lint (/Users/beckwith/Code/sloth/node_modules/gts/build/src/lint.js:54:25)
    at run (/Users/beckwith/Code/sloth/node_modules/gts/build/src/cli.js:86:36)
    at Object.<anonymous> (/Users/beckwith/Code/sloth/node_modules/gts/build/src/cli.js:102:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

Must have been fixed at some point :) Let us know if you're still having problems!
