### ISSUE TITLE
[Windows, Init] - Init error caused by paths containing spaces

### ISSUE THREAD

**Issue by vivid-fire** [google/gts#349]
It looks like it does not work with path containing spaces.

```javascript
$ npx gts init
Error: EEXIST: file already exists, mkdir 'C:\Users\Chris'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\npm.js:228:22)
    at C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\npm.js:266:24
    at C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\config\core.js:173:20)
    at C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\node_modules\mkdirp\index.js:47:53
C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Users\Chris Qiu\scoop\persist\nvm\nodejs\v10.15.3\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:189:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
Install for gts@latest failed with code 7
```

**Comment by JustinBeckwith** [comment]
We did a bunch of work in prior releases to add Windows CI, and I suspect we fixed this along the way.  I just verified that a `npx gts init` on a windows machine with the latest version works on a path with spaces :) Let us know if you're still having problems!
