### ISSUE TITLE
gts clean fails with file-not-found for tsconfig.json if it has c-style comments 

### ISSUE THREAD

**Issue by stari4ek** [google/gts#442]
`gts fix` works well:
```
astar@7u:~/dev/tvirl/develop/fb/functions$ gts fix
```
`gts clean` fails with `Not Found` for `tsconfig.json` which exists:
```
astar@7u:~/dev/tvirl/develop/fb/functions$ gts clean
Error: /home/astar/dev/tvirl/develop/fb/functions/tsconfig.json Not Found
    at getBase (/home/astar/dev/tvirl/develop/fb/functions/node_modules/gts/build/src/util.js:77:15)
    at async Object.clean (/home/astar/dev/tvirl/develop/fb/functions/node_modules/gts/build/src/clean.js:24:23)

astar@7u:~/dev/tvirl/develop/fb/functions$ cat /home/astar/dev/tvirl/develop/fb/functions/tsconfig.json 
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "lib",
    // override from google's one
    "lib": ["es2017"],
    "resolveJsonModule": true,
    // allows proper default export (used with ts-interface-builder)
    "esModuleInterop": true,
    // TODO: suppressed temporary. we do not want to resolve it for play-billing right now
    "noImplicitAny": false
  },
  "compileOnSave": true,
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ]
}

astar@7u:~/dev/tvirl/develop/fb/functions$ ls -la ./node_modules/gts/tsconfig-google.json
-rw-r--r-- 1 astar astar 441 окт 26  1985 ./node_modules/gts/tsconfig-google.json
```

Removing "comments" from `tsconfig.json` solves the issue.

It would be nice if better error message (failed to parse) is produced or it accepts such non-standard syntax (the rest works well with it)

**Comment by pastelmind** [comment]
I'm seeing a similar error when there are `//`-comments in `tsconfig.json`:

```
$ npm run clean

> display3@0.1.0 clean C:\Users\Phil\Documents\GitHub\display3
> gts clean

version: 12
SyntaxError: Error: C:\Users\Phil\Documents\GitHub\display3\tsconfig.json
Unexpected token / in JSON at position 114
    at JSON.parse (<anonymous>)
    at getBase (C:\Users\Phil\Documents\GitHub\display3\node_modules\gts\build\src\util.js:58:29)
    at async Object.clean (C:\Users\Phil\Documents\GitHub\display3\node_modules\gts\build\src\clean.js:25:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! display3@0.1.0 clean: `gts clean`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the display3@0.1.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Phil\AppData\Roaming\npm-cache\_logs\2020-12-29T11_54_44_103Z-debug.log
```

#571 seems to have stalled. It says a test has failed. Unfortunately, the logs have expired, so we don't know what the problem was.

Is there a way I can assist #571 getting merged?
