### ISSUE TITLE
npx gts init breaks Angular 9 project

### ISSUE THREAD

**Issue by nubianMONK** [google/gts#482]
Background:
An existing Angular 9 Project, with following basic stack:
Angular CLI: 9.1.1
Node: 12.6.0
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cdk                       9.2.0
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.0
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.1

Steps taken per installation of gts:
0. Backed Up the following: package.json, tsconfig.json and tslint.json
1. Per prescriptions provided within the readme.md file of the gts repo-
  a. Ran : npx gts init within the Angular 9 project directory
  b. Chose “N” not to overwrite version 3.8.3 to 3.8.0 of TypeScript
  c. Chose  "N" not to overwrite Node version 13.11.1 to 10.0.3
  d. Chose “y” to overwrite tsconfig.json
it in turn ran its course adding 192 packages.

Pre installation of gts the project's tsconfig.json was as such below:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

Post the installation of gts the tsconfig.json file was now as  such below:
{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "build"
  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ]
}

Knowing it was going to need a "target" and "library" properties, I updated to the following (A merge of the gts created tsconfig.json file and the original Angular 9 project tsconfig.json files:

{
  "extends": "./node_modules/gts/tsconfig-google.json",
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]

  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ],
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

Serving the Application, by running : ng serve --port 4201 , presents a broken project which prior to the install, will render the application locally @ port 4201

When I issue the following gts command: gts check *.ts i get the following:
Command 'gts' not found, but there are 17 similar ones.

NB:  I am using the Windows Subsystem Linux (Ubuntu) as my development environment.

Can you please help point in the right direction or resolve this issue if it seems to be an incompatibility with Angular 9 projects??

Looking forward to your response.

**Comment by ninezero90hy** [comment]
I faced the same problem 😭

**Comment by ninezero90hy** [comment]
- package.json
```
{
  "name": "niz-stateful-example",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "check": "gts check",
    "clean": "gts clean",
    "compile": "tsc",
    "fix": "gts fix",
    "prepare": "npm run compile",
    "pretest": "npm run compile",
    "posttest": "npm run check"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.1",
    "@angular/common": "~9.1.1",
    "@angular/compiler": "~9.1.1",
    "@angular/core": "~9.1.1",
    "@angular/forms": "~9.1.1",
    "@angular/platform-browser": "~9.1.1",
    "@angular/platform-browser-dynamic": "~9.1.1",
    "@angular/router": "~9.1.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.1",
    "@angular/language-service": "~9.1.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^10.0.3",
    "codelyzer": "^5.1.2",
    "gts": "^2.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.0"
  }
}
```

- error log
```
/project/workspace/github/niz-stateful-example/e2e/src/app.e2e-spec.ts
   2:32  error  "protractor" is not published  node/no-unpublished-import
   4:1   error  'describe' is not defined      no-undef
   7:3   error  'beforeEach' is not defined    no-undef
  11:3   error  'it' is not defined            no-undef
  13:5   error  'expect' is not defined        no-undef
  16:3   error  'afterEach' is not defined     no-undef
  19:5   error  'expect' is not defined        no-undef
  20:7   error  'jasmine' is not defined       no-undef

/project/workspace/github/niz-stateful-example/e2e/src/app.po.ts
  1:36  error  "protractor" is not published  node/no-unpublished-import

/project/workspace/github/niz-stateful-example/src/app/app.component.spec.ts
   5:1  error  'describe' is not defined    no-undef
   6:3  error  'beforeEach' is not defined  no-undef
  13:3  error  'it' is not defined          no-undef
  16:5  error  'expect' is not defined      no-undef
  19:3  error  'it' is not defined          no-undef
  22:5  error  'expect' is not defined      no-undef
  25:3  error  'it' is not defined          no-undef
  29:5  error  'expect' is not defined      no-undef

/project/workspace/github/niz-stateful-example/e2e/protractor.conf.js
   5:32  error  "jasmine-spec-reporter" is not published  node/no-unpublished-require
  25:13  error  "ts-node" is not published                node/no-unpublished-require
  28:5   error  'jasmine' is not defined                  no-undef

/project/workspace/github/niz-stateful-example/karma.conf.js
   9:15  error  "karma-jasmine" is not published                     node/no-unpublished-require
  10:15  error  "karma-chrome-launcher" is not published             node/no-unpublished-require
  11:15  error  "karma-jasmine-html-reporter" is not published       node/no-unpublished-require
  12:15  error  "karma-coverage-istanbul-reporter" is not published  node/no-unpublished-require
  13:15  error  "@angular-devkit/build-angular" is not published     node/no-unpublished-require

✖ 25 problems (25 errors, 0 warnings)

Error: Command failed with exit code 1: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern
    at makeError (/project/workspace/github/niz-stateful-example/node_modules/gts/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/project/workspace/github/niz-stateful-example/node_modules/gts/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/project/workspace/github/niz-stateful-example/node_modules/gts/build/src/cli.js:103:17) {
  shortMessage: 'Command failed with exit code 1: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  command: 'node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
ninezero@MacBook-Pro /p/w/g/niz-stateful-example (feature/1) [1]>
```

**Comment by iRockyZhou** [comment]
+1

**Comment by fjbatresv** [comment]
+1

Some update?

**Comment by JustinBeckwith** [comment]
nope, haven't had time to dig into it - if someone else wants to take a look, that would be awesome!

**Comment by gaeshi** [comment]
+1

**Comment by robgorham** [comment]
+1

**Comment by zer09** [comment]
So far this works for me.

```json
{
  "extends": [
    "./node_modules/gts/"
  ],
  "env": {
    "jasmine": true, // or mocha
    "browser": true
  },
// disable some rules
  "overrides": [
    {
      "files": [
        "**/*.conf.js",
        "**/*.po.ts",
        "**/test.ts",
        "**/zone-flags.ts"
      ],
      "rules": {
        "node/no-unpublished-require": "off",
        "node/no-unpublished-import": "off",
        "@typescript-eslint/no-explicit-any": "off"
      }
    }
  ]
}

```

references:
https://stackoverflow.com/questions/30018271/javascript-standard-style-does-not-recognize-mocha/38667441#38667441

https://github.com/mysticatea/eslint-plugin-node/issues/105#issuecomment-361518687

**Comment by juanilo** [comment]
I also broke my angular 10.1.7v
![image](https://user-images.githubusercontent.com/8930627/97135675-b86d3a80-172f-11eb-91ea-0f6956d8a50f.png)

**Comment by armingdev** [comment]
It also broke fresh new Angular 11 app. Can you please update this package for Angular 11?

**Comment by binoculars** [comment]
This works for me with Angular 11:

### .eslintignore

```
build/
dist/
*.conf.js
```

### .eslintrc.json

```json
{
  "extends": "./node_modules/gts/",
  "rules": {
    "node/no-unpublished-import": ["error", {
        "allowModules": ["protractor"]
    }]
  }
}
```
