### ISSUE TITLE
gts with Angular 11 compatiblity

### ISSUE THREAD

**Issue by armingdev** [google/gts#606]
Installing gts with a fresh installed Angular 11 app causes a lot of problems. Doing lint command, a lot of errors and fixing it one by one leading to new errors ... Example of errors (just part of them):
```
 25:20  error  Replace `()·{}` with `·()·{},`                                                                                             prettier/prettier
  28:13  error  "ts-node" is not published                                                                                                 node/no-unpublished-require
  29:66  error  Insert `,`                                                                                                                 prettier/prettier
  31:5   error  'jasmine' is not defined
```
Also lint command brake with this error:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/armingerina/.nvm/versions/node/v14.15.1/bin/node',
1 verbose cli   '/Users/armingerina/.nvm/versions/node/v14.15.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle demo-project@0.0.0~prelint: demo-project@0.0.0
6 info lifecycle demo-project@0.0.0~lint: demo-project@0.0.0
7 verbose lifecycle demo-project@0.0.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle demo-project@0.0.0~lint: PATH: /Users/armingerina/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/armingerina/Code/test-projects/demo-project/node_modules/.bin:/Users/armingerina/.nvm/versions/node/v14.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/armingerina/.dotnet/tools
9 verbose lifecycle demo-project@0.0.0~lint: CWD: /Users/armingerina/Code/test-projects/demo-project
10 silly lifecycle demo-project@0.0.0~lint: Args: [ '-c', 'gts lint' ]
11 silly lifecycle demo-project@0.0.0~lint: Returned: code: 1  signal: null
12 info lifecycle demo-project@0.0.0~lint: Failed to exec lint script
13 verbose stack Error: demo-project@0.0.0 lint: `gts lint`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/armingerina/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/armingerina/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid demo-project@0.0.0
15 verbose cwd /Users/armingerina/Code/test-projects/demo-project
16 verbose Darwin 19.6.0
17 verbose argv "/Users/armingerina/.nvm/versions/node/v14.15.1/bin/node" "/Users/armingerina/.nvm/versions/node/v14.15.1/bin/npm" "run" "lint"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error demo-project@0.0.0 lint: `gts lint`
22 error Exit status 1
23 error Failed at the demo-project@0.0.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

When we can expect an update for this package with the latest configuration files since the current ones make a lot of problems?
Thanks

**Comment by JustinBeckwith** [comment]
Greetings!  We don't actively support Angular with `gts`, and it's not something we specifically tried to do.  There's an existing issue over here for it:
https://github.com/google/gts/issues/482

If anyone would like to contribute - we're happy to accept patches!  But we're not planning on getting here any time soon.
