### ISSUE TITLE
Error: Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Vadorequest** [google/gts#638]
I'm getting the following error during linting (`gts lint`):

```
/Users/vadorequest/dev/spottedio/lynx-project-app/sentry.client.config.js
  6:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/Users/vadorequest/dev/spottedio/lynx-project-app/sentry.server.config.js
  6:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 4 problems (2 errors, 2 warnings)

Error: Command failed with exit code 1: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern
    at makeError (/Users/vadorequest/dev/spottedio/lynx-project-app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/vadorequest/dev/spottedio/lynx-project-app/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async run (/Users/vadorequest/dev/spottedio/lynx-project-app/node_modules/gts/build/src/cli.js:123:17) {
  shortMessage: 'Command failed with exit code 1: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  command: 'node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit hook exited with code 1 (error)

```

Because of this file:
```js
// This file configures the initialization of Sentry on the server.
// The config you add here will be used whenever the server handles a request.
// https://docs.sentry.io/platforms/javascript/guides/nextjs/
// https://sentry.io/spottedio-6l/lynx-project-app/getting-started/javascript-nextjs/

import * as Sentry from '@sentry/nextjs';

const SENTRY_DSN = process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN;

Sentry.init({
  dsn:
    SENTRY_DSN ||
    'https://00f91da3fe554595805f71556dc0a805@o656681.ingest.sentry.io/5762837',
  // Note: if you want to override the automatic release value, do not set a
  // `release` value here - use the environment variable `SENTRY_RELEASE`, so
  // that it will also get attached to your source maps

  // Set tracesSampleRate to 1.0 to capture 100%
  // of transactions for performance monitoring.
  // We recommend adjusting this value in production
  // https://docs.sentry.io/platforms/javascript/configuration/sampling/
  tracesSampleRate: 1.0,
});

```

There seems to be a misconfiguration, i'm not sure how to fix that. Any hint? :)

**Comment by Vadorequest** [comment]
I can't, it was too long ago, don't have access to that project anymore. Closing.
