### ISSUE TITLE
4.x.x release of breaks in some contexts

### ISSUE THREAD

**Issue by bcoe** [google/gts#708]
I am receiving the following error when trying to run the 4.x release of gts on a client library:

```
> gts check

version: 14

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Cannot read config file: /Users/bencoe/google/nodejs-vision/samples/.eslintrc.yml
Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
    at Object.safeLoad (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/node_modules/js-yaml/index.js:10:11)
    at loadYAMLConfigFile (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/lib/config-array-factory.js:161:21)
    at loadConfigFile (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/lib/config-array-factory.js:319:20)
    at ConfigArrayFactory.loadInDirectory (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/lib/config-array-factory.js:502:34)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/bencoe/google/nodejs-vision/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
    at FileEnumerator._iterateFilesRecursive (/Users/bencoe/google/nodejs-vision/node_modules/eslint/lib/cli-engine/file-enumerator.js:445:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (/Users/bencoe/google/nodejs-vision/node_modules/eslint/lib/cli-engine/file-enumerator.js:492:33)
    at _iterateFilesRecursive.next (<anonymous>)
```

**Comment by bcoe** [comment]
Refs: #704

**Comment by bcoe** [comment]
I believe this was ultimately an issue with a stale `package-lock.json`.
